export const PokemonesEs = [
  {
    id: "001",
    name: "Bulbasaur",
    img: "/Images/bulbasaur.png",
    gif: "/Images/bulbasaur.gif",
    shiny: "/Images/bulbasaurs.gif",
    types: ["Planta", "Veneno"],
    weight: 6.9,
    height: 0.7,
    moves: ["Clorofila", "Desarrollo"],
    description:
      "Tiene la semilla de una planta en su espalda desde el día de su nacimiento. La semilla crece lentamente.",
    stats: {
      hp: "045",
      atk: "049",
      def: "049",
      satk: "065",
      sdef: "065",
      spd: "045",
    },
    language: "es",
  },

  {
    id: "004",
    name: "Charmander",
    img: "/Images/charmander.png",
    gif: "/Images/charmander.gif",
    shiny: "/Images/charmanders.gif",
    types: ["Fuego"],
    weight: 8.5,
    height: 0.6,
    moves: ["Mega Puño", "Puño de Fuego"],
    description:
      "Tiene preferencia por cosas calientes. Cuando llueve, se dice que sale vapor de la punta de su cola.",
    stats: {
      hp: "039",
      atk: "052",
      def: "043",
      satk: "060",
      sdef: "050",
      spd: "065",
    },
    language: "es",
  },

  {
    id: "007",
    name: "Squirtle",
    img: "/Images/squirtle.png",
    gif: "/Images/squirtle.gif",
    shiny: "/Images/squirtles.gif",
    types: ["Agua"],
    weight: 9.0,
    height: 0.5,
    moves: ["Torrente", "Danza Lluvia"],
    description:
      "Cuando introduce su largo cuello en su caparazon, escucpe agua con gran fuerza.",
    stats: {
      hp: "044",
      atk: "048",
      def: "065",
      satk: "050",
      sdef: "064",
      spd: "043",
    },
    language: "es",
  },

  {
    id: "012",
    name: "Butterfree",
    img: "/Images/butterfree.png",
    gif: "/Images/butterfree.gif",
    shiny: "/Images/butterfrees.gif",
    types: ["Insecto", "Volador"],
    weight: 32.0,
    height: 1.1,
    moves: ["Ojos Compuestos", "Vuelo"],
    description:
      "En pelea, aletea sus alas a gran velocidad para liberar polvo altamente toxico al aire.",
    stats: {
      hp: "060",
      atk: "045",
      def: "050",
      satk: "090",
      sdef: "080",
      spd: "070",
    },
    language: "es",
  },

  {
    id: "025",
    name: "Pikachu",
    img: "/Images/pikachu.png",
    gif: "/Images/pikachu.gif",
    shiny: "/Images/pikachus.gif",
    types: ["Electrico"],
    weight: 6.0,
    height: 0.4,
    moves: ["Mega Golpe", "Impactrueno"],
    description:
      "Puede generar mucha electricidad, tiene cachetes super suaves y elasticos.",
    stats: {
      hp: "035",
      atk: "055",
      def: "040",
      satk: "050",
      sdef: "050",
      spd: "090",
    },
    language: "es",
  },

  {
    id: "304",
    name: "Aron",
    img: "/Images/aron.png",
    gif: "/Images/aron.gif",
    shiny: "/Images/arons.gif",
    types: ["Acero", "Roca"],
    weight: 60.0,
    height: 0.4,
    moves: ["Robusto", "Cabeza Piedra"],
    description:
      "Come menas de metales -y a veces vias de tren- para crear una carcaza de metal que proteje su cuerpo.",
    stats: {
      hp: "050",
      atk: "070",
      def: "100",
      satk: "040",
      sdef: "040",
      spd: "030",
    },
    language: "es",
  },

  {
    id: "152",
    name: "Mew",
    img: "/Images/mew.png",
    gif: "/Images/mew.gif",
    shiny: "/Images/mews.gif",
    types: ["Psiquico"],
    weight: 4.0,
    height: 0.4,
    moves: ["Sincronizar"],
    description:
      "En el microscopio puede observarce el pelo corto, fino y delicado de este Pokemon.",
    stats: {
      hp: "100",
      atk: "100",
      def: "100",
      satk: "100",
      sdef: "100",
      spd: "100",
    },
    language: "es",
  },

  {
    id: "132",
    name: "Ditto",
    img: "/Images/ditto.png",
    gif: "/Images/ditto.gif",
    shiny: "/Images/dittos.gif",
    types: ["Normal"],
    weight: 4.0,
    height: 0.3,
    moves: ["Agilidad", "Impostor"],
    description:
      "Puede reconstituir el total de su estructura celular para cambiar su apariencia, pero vuelve a la normalidad cuando se relaja.",
    stats: {
      hp: "048",
      atk: "048",
      def: "048",
      satk: "048",
      sdef: "048",
      spd: "048",
    },
    language: "es",
  },

  {
    id: "092",
    name: "Gastly",
    img: "/Images/gastly.png",
    gif: "/Images/gastly.gif",
    shiny: "/Images/gastlys.gif",
    types: ["Fantasma"],
    weight: 0.1,
    height: 1.3,
    moves: ["Levitar"],
    description:
      "Nacido de gases, cualquiera se desmayaría si fuera engullido por su cuerpo gaseoso, que contiene veneno.",
    stats: {
      hp: "030",
      atk: "035",
      def: "030",
      satk: "100",
      sdef: "035",
      spd: "080",
    },
    language: "es",
  },
];
